[book]
title = "nhp-dwiproc documentation"
authors = ["Jason Kai"]
description = "This book provides documentation for nhp-dwiproc."
language = "en"
src = "src"

[preprocessor.langtabs]
command = "mdbook-langtabs"

[output.html]
no-section-label = true
additional-css = ["custom.css", "langtabs.css"]
additional-js = ["langtabs.js"]

[output.html.fold]
enable = true
level = 1
