name: Python Tests & Linting

on:
  push:
    branches:
      - main
      - dev

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup uv
        uses: astral-sh/setup-uv@v7
      - name: Run tests
        run: >
          uv run --frozen pytest \
            --junitxml=pytest.xml \
            --cov-report=term-missing:skip-covered \
            --cov-report=xml:coverage.xml \
            --cov=src tests \
            --log-level=DEBUG \
            --verbose
      - name: Upload coverage to Codecov # Repository specific token!
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
  check_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup uv
        uses: astral-sh/setup-uv@v7
      - name: Ruff format
        run: uv run ruff format --check src

      - name: Ruff check
        run: uv run ruff check src

      - name: Ty check
        run: uv run ty check src
